### ISSUE TITLE
Add travis

### ISSUE THREAD

**Issue by fsmanuel** [halo/bender#6]
``` yml
language: ruby
cache: bundler

sudo: false
rvm:
  - 2.2.0
install: bundle install
script:
#  - bundle exec rspec
  - bundle exec rubocop
```
